# Generated by Django 3.2.8 on 2021-11-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0003_auto_20211106_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
