# Generated by Django 3.2.8 on 2021-11-19 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0007_auto_20211111_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcart',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorder',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
